#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudAwesome.Dataverse.Core.EarlyBoundEntities
{
	
	
	/// <summary>
	/// The state of this component.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum ComponentState
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Deleted = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DeletedUnpublished = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Published = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Unpublished = 1,
	}
	
	/// <summary>
	/// The Allowed Custom Processing Step Type
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum CustomApi_AllowedCustomProcessingStepType
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AsyncOnly = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		None = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SyncAndAsync = 2,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum CustomApi_BindingType
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Entity = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		EntityCollection = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Global = 0,
	}
	
	/// <summary>
	/// Status of the Custom API
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum CustomApi_StateCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 1,
	}
	
	/// <summary>
	/// Reason for the status of the Custom API
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum CustomApi_StatusCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 2,
	}
	
	/// <summary>
	/// Custom API Field Types
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum CustomApiFieldType
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Boolean = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Datetime = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Decimal = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Entity = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Entitycollection = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Entityreference = 5,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Float = 6,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Guid = 12,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Integer = 7,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Money = 8,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Picklist = 9,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		String = 10,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Stringarray = 11,
	}
	
	/// <summary>
	/// Status of the Custom API Request Parameter
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum CustomApiRequestParameter_StateCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 1,
	}
	
	/// <summary>
	/// Reason for the status of the Custom API Request Parameter
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum CustomApiRequestParameter_StatusCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 2,
	}
	
	/// <summary>
	/// Status of the Custom API Response Property
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum CustomApiResponseProperty_StateCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 1,
	}
	
	/// <summary>
	/// Reason for the status of the Custom API Response Property
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum CustomApiResponseProperty_StatusCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 2,
	}
	
	/// <summary>
	/// The secret store where the secret is persisted.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum EnvironmentVariableDefinition_SecretStore
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AzureKeyVault = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MicrosoftDataverse = 1,
	}
	
	/// <summary>
	/// Status of the Environment Variable Definition
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum EnvironmentVariableDefinition_StateCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 1,
	}
	
	/// <summary>
	/// Reason for the status of the Environment Variable Definition
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum EnvironmentVariableDefinition_StatusCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 2,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum EnvironmentVariableDefinition_Type
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Boolean = 100000002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DataSource = 100000004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Json = 100000003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Number = 100000001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Secret = 100000005,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		String = 100000000,
	}
	
	/// <summary>
	/// Status of the Environment Variable Value
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum EnvironmentVariableValue_StateCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 1,
	}
	
	/// <summary>
	/// Reason for the status of the Environment Variable Value
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum EnvironmentVariableValue_StatusCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 2,
	}
	
	/// <summary>
	/// Status of the Custom API Ruleset Configuration
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Msdyn_CustomApiRuleSetConfiguration_StateCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 1,
	}
	
	/// <summary>
	/// Reason for the status of the Custom API Ruleset Configuration
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Msdyn_CustomApiRuleSetConfiguration_StatusCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 2,
	}
	
	/// <summary>
	/// Authentication Type for the Web sources like AzureWebApp, for example 0=BasicAuth
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum PluginAssembly_AuthType
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Basicauth = 0,
	}
	
	/// <summary>
	/// Information about how the plugin assembly is to be isolated at execution time; None / Sandboxed / External.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum PluginAssembly_IsolationMode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		External = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		None = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Sandbox = 2,
	}
	
	/// <summary>
	/// Location of the assembly, for example 0=database, 1=on-disk, 2=Normal, 3=AzureWebApp.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum PluginAssembly_SourceType
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Azurewebapp = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Database = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Disk = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FileStore = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Normal = 2,
	}
	
	/// <summary>
	/// Status of the Plugin Package
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum PluginPackage_StateCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 1,
	}
	
	/// <summary>
	/// Reason for the status of the Plugin Package
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum PluginPackage_StatusCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 2,
	}
	
	/// <summary>
	/// Type of address for address 1, such as billing, shipping, or primary address.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Publisher_Address1_AddressTypeCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DefaultValue = 1,
	}
	
	/// <summary>
	/// Method of shipment for address 1.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Publisher_Address1_ShippingMethodCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DefaultValue = 1,
	}
	
	/// <summary>
	/// Type of address for address 2. such as billing, shipping, or primary address.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Publisher_Address2_AddressTypeCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DefaultValue = 1,
	}
	
	/// <summary>
	/// Method of shipment for address 2.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Publisher_Address2_ShippingMethodCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DefaultValue = 1,
	}
	
	/// <summary>
	/// Identifies if a plug-in should be executed from a parent pipeline, a child pipeline, or both.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum SdkMessageProcessingStep_InvocationSource
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Child = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Internal = -1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Parent = 0,
	}
	
	/// <summary>
	/// Run-time mode of execution, for example, synchronous or asynchronous.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum SdkMessageProcessingStep_Mode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Asynchronous = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Synchronous = 0,
	}
	
	/// <summary>
	/// Stage in the execution pipeline that the SDK message processing step is in.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum SdkMessageProcessingStep_Stage
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FinalPostOperationForInternalUseOnly = 55,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InitialPreOperationForInternalUseOnly = 5,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InternalPostOperationAfterExternalPluginsForInternalUseOnly = 45,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InternalPostOperationBeforeExternalPluginsForInternalUseOnly = 35,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InternalPreOperationAfterExternalPluginsForInternalUseOnly = 25,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InternalPreOperationBeforeExternalPluginsForInternalUseOnly = 15,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MainOperationForInternalUseOnly = 30,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PostCommitStageFiredAfterTransactionCommitForInternalUseOnly = 90,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PostOperation = 40,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PostOperationDeprecated = 50,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PreCommitStageFiredBeforeTransactionCommitForInternalUseOnly = 80,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PreOperation = 20,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PreValidation = 10,
	}
	
	/// <summary>
	/// Status of the SDK message processing step.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum SdkMessageProcessingStep_StateCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Disabled = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Enabled = 0,
	}
	
	/// <summary>
	/// Reason for the status of the SDK message processing step.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum SdkMessageProcessingStep_StatusCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Disabled = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Enabled = 1,
	}
	
	/// <summary>
	/// Deployment that the SDK message processing step should be executed on; server, client, or both.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum SdkMessageProcessingStep_SupportedDeployment
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Both = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MicrosoftDynamics365ClientForOutlookOnly = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ServerOnly = 0,
	}
	
	/// <summary>
	/// Type of image requested.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum SdkMessageProcessingStepImage_ImageType
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Both = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Postimage = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Preimage = 0,
	}
	
	/// <summary>
	/// Authentication type for Service Bus
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum ServiceEndpoint_AuthType
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AccessKey = 8,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Acs = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ConnectionString = 7,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		HttpHeader = 5,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		HttpQueryString = 6,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ManagedIdentity = 9,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		NotSpecified = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SasKey = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SasToken = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		WebhookKey = 4,
	}
	
	/// <summary>
	/// Connection mode.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum ServiceEndpoint_ConnectionMode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Federated = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Normal = 1,
	}
	
	/// <summary>
	/// Contract type.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum ServiceEndpoint_Contract
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		EventGrid = 9,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		EventHub = 7,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ManagedDataLake = 10,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Oneway = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Queue = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		QueuePersistent = 6,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Rest = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Topic = 5,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Twoway = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Webhook = 8,
	}
	
	/// <summary>
	/// Character encoding used for messages sent to a service endpoint
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum ServiceEndpoint_MessageCharSet
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Default = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Utf8 = 1,
	}
	
	/// <summary>
	///  Format type.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum ServiceEndpoint_MessageFormat
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		BinaryXml = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Json = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		TextXml = 3,
	}
	
	/// <summary>
	/// Format for Service Bus Namespace
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum ServiceEndpoint_NamespaceFormat
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		NamespaceAddress = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		NamespaceName = 1,
	}
	
	/// <summary>
	/// Schema type for Event Grid
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum ServiceEndpoint_SchemaType
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CloudEvents = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		EventGrid = 1,
	}
	
	/// <summary>
	/// User claim value type.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum ServiceEndpoint_UserClaim
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		None = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Userid = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Userinfo = 3,
	}
	
	/// <summary>
	/// Business Process Type.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Workflow_BusinessProcessType
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		BusinessFlow = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		TaskFlow = 1,
	}
	
	/// <summary>
	/// Category of the process.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Workflow_Category
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Action = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AiFlow = 7,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		BusinessProcessFlow = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		BusinessRule = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DesktopFlow = 6,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Dialog = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ModernFlow = 5,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		WebClientApiFlow = 9000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Workflow = 0,
	}
	
	/// <summary>
	/// Mode of the process.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Workflow_Mode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Background = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RealTime = 1,
	}
	
	/// <summary>
	/// Type of the Modern Flow process.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Workflow_ModernFlowType
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Copilotstudioflow = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Powerautomateflow = 0,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Workflow_ProcessTriggersCope
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Entity = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Form = 1,
	}
	
	/// <summary>
	/// Specifies the system user account under which a workflow executes
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Workflow_RunAs
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CallingUser = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Owner = 0,
	}
	
	/// <summary>
	/// Workflow scope.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Workflow_Scope
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		BusinessUnit = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Organization = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ParentChildBusinessUnits = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		User = 1,
	}
	
	/// <summary>
	/// Stage in which the Workflow executes
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Workflow_Stage
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PostOperation = 40,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PreOperation = 20,
	}
	
	/// <summary>
	/// Status of the workflow
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Workflow_StateCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Activated = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Draft = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Suspended = 2,
	}
	
	/// <summary>
	/// Reason for the status of the workflow
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Workflow_StatusCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Activated = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Companydlpviolation = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Draft = 1,
	}
	
	/// <summary>
	/// Type of workflow throttling behavior.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Workflow_ThrottlingBehavior
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		None = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Tenantpool = 1,
	}
	
	/// <summary>
	/// Workflow type.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Workflow_Type
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Activation = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Definition = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Template = 3,
	}
	
	/// <summary>
	/// Type of the Desktop Flow process.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Workflow_UiFlowType
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PowerAutomateDesktop = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Recording = 101,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SeleniumIde = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Test = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		WindowsRecorderV1 = 0,
	}
}
#pragma warning restore CS1591
